name: Android Build and Release

on: [ push, pull request ]

jobs:

  build:
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Print Java version
        run: javac -version
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Fix SDK
        run: sudo chmod -R a+w /usr/local/lib/android/sdk
      - name: Run Test
        run: ./gradlew test
      - name: Build Project
        run: ./gradlew assemble

