name: Feature branch test and build

on:
  push:
    branches:
      - feature

  pull_request:
    branches:
      - feature

jobs:
  test:
    name: Running local test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Fix Android SDK
        run: sudo chmod -R a+w /usr/local/lib/android/sdk

      - name: Run Tests
        run: ./gradlew test

  build:
    name: Build Project

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew assembleDebug --stacktrace