name: Staging branch test, build, and debug APK

on:
  push:
    branches:
      - staging

  pull_request:
    branches:
      - staging

jobs:
  test:
    name: Running local test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Fix Android SDK
        run: sudo chmod -R a+w /usr/local/lib/android/sdk

      - name: Run Tests
        run: ./gradlew test


  build:
    name: Build Project

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew assemble


  debugApk:
    name: Generate Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Fix Android SDK
        run: sudo chmod -R a+w /usr/local/lib/android/sdk

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk